import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { FacadeConfigInputSchema, FacadeConfigSchema } from '../src/config/facade-config.js';
import { ReleasePageManifestSchema } from '../src/manifest/release-page-manifest.js';
import { validateManifestSemantics } from '../src/manifest/semantic-validation.js';
import { RepositorySnapshotSchema } from '../src/source/repository-snapshot.js';

function fixture(name: string): unknown { return JSON.parse(readFileSync(fileURLToPath(new URL(`../../../fixtures/repositories/${name}`, import.meta.url)), 'utf8')); }
describe('manifest validation', () => {
  it('accepts an offline fixture with distinct artifacts and linked signature', () => { const manifest = ReleasePageManifestSchema.parse(fixture('basic-release.json')); expect(validateManifestSemantics(manifest)).toEqual([]); });
  it('reports a missing signature artifact reference', () => { const manifest = ReleasePageManifestSchema.parse(fixture('invalid-signature.json')); expect(validateManifestSemantics(manifest)).toEqual([{ path: 'assets.signature.signatureFor', message: 'signatureFor must reference an existing artifact' }]); });
  it('reports duplicate asset IDs as semantic diagnostics', () => { const manifest = ReleasePageManifestSchema.parse({ schemaVersion: 0, productName: 'Duplicate', releaseTag: 'v0', assets: [{ id: 'same', label: 'A', downloadUrl: 'https://example.test/a', os: 'windows', kind: 'artifact', evidence: {} }, { id: 'same', label: 'B', downloadUrl: 'https://example.test/b', os: 'windows', kind: 'artifact', evidence: {} }] }); expect(validateManifestSemantics(manifest)).toEqual([{ path: 'assets.same', message: 'asset IDs must be unique' }]); });
  it('rejects non-HTTP download URLs', () => { expect(() => ReleasePageManifestSchema.parse({ schemaVersion: 0, productName: 'Unsafe', releaseTag: 'v0', assets: [{ id: 'unsafe', label: 'Unsafe', downloadUrl: 'ftp://example.test/a', os: 'unknown', kind: 'other', evidence: {} }] })).toThrow(); });
  it('keeps a conflicting-name fixture explicitly unknown', () => { const manifest = ReleasePageManifestSchema.parse(fixture('conflicting-name.json')); expect(manifest.assets[0]?.os).toBe('unknown'); expect(validateManifestSemantics(manifest)).toEqual([]); });
  it('parses the tagged public source snapshot offline', () => { const snapshot = RepositorySnapshotSchema.parse(fixture('basic-release.source.json')); expect(snapshot.repository.fullName).toBe('cli/cli'); expect(snapshot.release.tagName).toBe('v2.100.0'); expect(snapshot.assets).toHaveLength(4); });
  it('reports evidence for an unsupported field', () => { const manifest = ReleasePageManifestSchema.parse({ schemaVersion: 0, productName: 'Evidence', releaseTag: 'v0', assets: [{ id: 'asset', label: 'Asset', downloadUrl: 'https://example.test/asset', os: 'unknown', kind: 'other', evidence: { arch: { source: 'filename-rule', detail: 'x64 token' } } }] }); expect(validateManifestSemantics(manifest)).toEqual([{ path: 'assets.asset.evidence.arch', message: 'evidence must reference a supported asset field' }]); });
  it('reports duplicate download URLs', () => { const manifest = ReleasePageManifestSchema.parse({ schemaVersion: 0, productName: 'Duplicate URLs', releaseTag: 'v0', assets: [{ id: 'first', label: 'First', downloadUrl: 'https://example.test/shared', os: 'unknown', kind: 'other', evidence: {} }, { id: 'second', label: 'Second', downloadUrl: 'https://example.test/shared', os: 'unknown', kind: 'other', evidence: {} }] }); expect(validateManifestSemantics(manifest)).toEqual([{ path: 'assets.second.downloadUrl', message: 'asset download URLs must be unique' }]); });
  it('reports invalid signature usage and unpopulated evidence references', () => { const manifest = ReleasePageManifestSchema.parse({ schemaVersion: 0, productName: 'Signature semantics', releaseTag: 'v0', assets: [{ id: 'target', label: 'Target', downloadUrl: 'https://example.test/target', os: 'unknown', kind: 'artifact', evidence: {} }, { id: 'non-signature', label: 'Non-signature', downloadUrl: 'https://example.test/non-signature', os: 'unknown', kind: 'artifact', signatureFor: 'target', evidence: {} }, { id: 'missing-signature-target', label: 'Missing signature target', downloadUrl: 'https://example.test/missing-signature-target', os: 'unknown', kind: 'signature', evidence: {} }, { id: 'missing-evidence-field', label: 'Missing evidence field', downloadUrl: 'https://example.test/missing-evidence-field', os: 'unknown', kind: 'other', evidence: { signatureFor: { source: 'project-config', detail: 'not set' } } }] }); expect(validateManifestSemantics(manifest)).toEqual([{ path: 'assets.non-signature.signatureFor', message: 'only signature assets may declare signatureFor' }, { path: 'assets.missing-signature-target.signatureFor', message: 'signature assets must reference an artifact' }, { path: 'assets.missing-evidence-field.evidence.signatureFor', message: 'evidence must reference a populated asset field' }]); });
  it('requires a tag when configuration selects tag strategy', () => { expect(() => FacadeConfigSchema.parse({ schema: 1, repository: 'owner/repo', release: { strategy: 'tag' } })).toThrow(); });
  it('rejects a tag for github-latest and unknown configuration keys', () => { expect(() => FacadeConfigSchema.parse({ schema: 1, repository: 'owner/repo', release: { strategy: 'github-latest', tag: 'v1.2.3' } })).toThrow(); expect(() => FacadeConfigSchema.parse({ schema: 1, repository: 'owner/repo', release: { strategy: 'github-latest' }, typo: true })).toThrow(); });
  it('accepts each unambiguous release strategy', () => { expect(FacadeConfigSchema.parse({ schema: 1, repository: 'owner/repo', release: { strategy: 'github-latest' } }).release).toEqual({ strategy: 'github-latest' }); expect(FacadeConfigSchema.parse({ schema: 1, repository: 'owner/repo', release: { strategy: 'tag', tag: 'v1.2.3' } }).release).toEqual({ strategy: 'tag', tag: 'v1.2.3' }); });
  it('accepts minimal repository YAML before inference and defaults are applied', () => { expect(FacadeConfigInputSchema.parse({ schema: 1 })).toEqual({ schema: 1 }); });
  it('rejects credentials in repository YAML', () => { expect(() => FacadeConfigInputSchema.parse({ schema: 1, token: 'secret' })).toThrow(); });
});
